### PR TITLE
Neurocommand updater

### PR DESCRIPTION
**Pull request by aswinnarayanan**
Added neurocommand updater app

### CODE REVIEW

**Comment by stebo85** [comment]
Dear @aswinnarayanan 

- great addition :)

I just tested it on nectar and there we get a permission error:
image

because this directory is owned by root.

**Comment by stebo85** [comment]
would we need a chmod here? https://github.com/NeCTAR-RC/bumblebee-images/blob/master/ansible/roles/neurodesk/tasks/neurocommand.yml

**Comment by aswinnarayanan** [comment]
Should we add a generic check and escalate to sudo on the updater.
So if neurocommand update triggers a permissions error, it prompts the user to retry as sudo?

**Comment by stebo85** [comment]
yes, possible?

**Comment by stebo85** [comment]
then we wouldn't need to change the bumblebee image :)

**Pull request merged**
