### PR TITLE
made container list more userfriendly

### PR DESCRIPTION
**Pull request by stebo85**
problems of the old list:
- had duplicate entries
- the shell command produced wasn't very readable

new list: 
- shows categories as well
- is based on log.txt from cvmfs
- repeats instruction at the end

### CODE REVIEW

**Comment by aswinnarayanan** [comment]
Dont merge. The lines with "------              " are breaking. I'll add some changes

**Comment by aswinnarayanan** [comment]
@stebo85

Does this look okay to you?

**Comment by stebo85** [comment]
yes, that looks nice :)

**Comment by stebo85** [comment]
@aswinnarayanan, the only problem is that it doesn't list the whole category and it cuts it off:
image

**Comment by stebo85** [comment]
was there a particular reason you truncated it with
```
      appcat=$(echo ${arrayIn[3]} | cut -c 12-)                                                                                                                                              
```
?

**Comment by stebo85** [comment]
oh, I see why you did the -c 12- this is not causing the truncation

**Comment by stebo85** [comment]
```
      appcat=$(echo ${arrayIn[@]:3} | cut -c 12-)                                                                                                                                            
```

does the trick :)

**Comment by stebo85** [comment]
ok, found a slightly more readable way (and more performant way) and this also gets rid of the comma at the end:
```
    appcat=${arrayIn[@]:3}
    appcat_clean=${appcat:11:-1}  
```

**Comment by stebo85** [comment]
This is the final result:
image

**Comment by aswinnarayanan** [comment]
Looks great!! Perfect

**Pull request merged**
