### PR TITLE
Matlab

### PR DESCRIPTION
**Pull request by civier**
Matlab IDE 2022a

### CODE REVIEW

**Comment by stebo85** [comment]
Cool - that looks great :)

**Comment by stebo85** [comment]
Dear @civier 

Thank you for working on Matlab :)

There a few issues that need to be addressed:
1) The README file lacks a bit information. Can you add how to download a license file and where to place it so that this works?
2) When you open matlab and try to activate a license it tries to store the license locally inside the container under /home/matlab which fails because it is a writable filesystem. If you can changes this to the general ~/ directory it will end up in the writable homedirectory of the user

Kind regards
Steffen

**Comment by civier** [comment]
I updated the readme and made a small change to Neurodesktop to solve the issue.
Let me know if there is anything else that needs to be addressed.

**Comment by stebo85** [comment]
Dear @civier,

Thank you for updating the README. This is great!

The problem is that changing the user the way you did it in Neurodesktop will not solve the problem - because it get's changed on startup depending on the user id who starts the container.

I think the correct solution would be to change the matlab container so that it works on any user ID.

@aswinnarayanan - what do you think?

**Comment by aswinnarayanan** [comment]
Agreed, hardcoded uid will get overridden currently. Arbitrary uid/gid could introduce issues for neurodesktop since users might mount network shares and want r/w, or due to various configurations. And these issues might not be relevant to the VDI, so they can hardcode.

**Comment by civier** [comment]
Yes. I now see it's more complicated than I thought. Give me some time, and I will make some changes that will at least allow to run MATLAB on the VDS.

**Comment by civier** [comment]
I will post an approx. completion date when I manage to set aside some time for it.

**Pull request merged**
