### PR TITLE
Added mrtrix3src (latest version) to the apps list.

### PR DESCRIPTION
**Pull request by timrosenow**
Added the mrtrix3src command to apps.json, as per https://github.com/NeuroDesk/neurocontainers/issues/721

### CODE REVIEW

**Review by stebo85 — CHANGES_REQUESTED** [review]
The syntax is not correct. I needs the version after the name and the comma needs to be moved.

instead of:
 ```
            "mrtrix3src": {
                "version": "latest",
                "exec": ""
            },
```

it needs to be:

```
            },
            "mrtrix3src latest": {
                "version": "latest",
                "exec": ""
            }
```

**Comment by timrosenow** [comment]
My apologies, I have fixed those typos.

**Comment by stebo85** [comment]
wonderful - that should work :)

**Comment by timrosenow** [comment]
Thank you so much


Dr Tim Rosenow

NIF Facility Fellow | CMCA Platform Leader - Preclinical MRI

National Imaging Facility<http://www.anif.org.au/> @ Centre for Microscopy Characterisation and Analysis<http://cmca.uwa.edu.au/>

The University of Western Australia •  M519   35 Stirling Hwy Perth WA 6009 Australia

T +61 8 6151 1023  •  M +61 423 266 880  •  E ***@***.******@***.***>

[cid:ae3d189d-c1de-4d40-bc3b-61e7b3516b9c]

[A black text on a black background  Description automatically generated]




________________________________

**Comment by stebo85** [comment]
Thank you! I know we need to make this process easier and we are working on it! I hope we have updates on this soon :)

**Comment by timrosenow** [comment]
All good, I appreciate the work you guys put in!


Dr Tim Rosenow

NIF Facility Fellow | CMCA Platform Leader - Preclinical MRI

National Imaging Facility<http://www.anif.org.au/> @ Centre for Microscopy Characterisation and Analysis<http://cmca.uwa.edu.au/>

The University of Western Australia •  M519   35 Stirling Hwy Perth WA 6009 Australia

T +61 8 6151 1023  •  M +61 423 266 880  •  E ***@***.******@***.***>

[cid:7f450b22-ada4-44dc-97b0-1347ec0f017d]

[A black text on a black background  Description automatically generated]




________________________________

**Pull request merged**
